# Generated by Django 2.2.9 on 2020-12-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaExpressRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, db_index=True, editable=False, help_text='System generated unique Identifier for this request', max_length=250, null=True, unique=True)),
                ('initialized_by', models.CharField(blank=True, help_text='This is the email address or username of the user who initialized this request if they are authenticated.', max_length=250, null=True)),
                ('timestamp', models.CharField(max_length=250, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.BigIntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('account_reference', models.CharField(db_index=True, max_length=120, null=True)),
                ('transaction_description', models.CharField(blank=True, max_length=130, null=True)),
                ('merchant_request_id', models.CharField(blank=True, db_index=True, max_length=254, null=True, unique=True)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, max_length=254, null=True, unique=True)),
                ('response_code', models.CharField(blank=True, max_length=250, null=True)),
                ('response_description', models.TextField(blank=True, null=True)),
                ('customer_message', models.TextField(blank=True, null=True)),
                ('callback_url', models.CharField(blank=True, help_text='The callback provided during the making of the request', max_length=250, null=True)),
                ('business_shortcode', models.CharField(max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date updated')),
                ('status', models.CharField(blank=True, choices=[('Successful', 'Successful - Successful request'), ('Processing', 'Processing - Waiting for Mpesa Response'), ('Failed', 'Failed - Failed request'), ('Disputed', 'Disputed - Payment has no Source')], max_length=200, null=True)),
                ('result_code', models.CharField(blank=True, max_length=250, null=True)),
                ('result_description', models.TextField(blank=True, null=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=254, null=True)),
                ('transaction_date', models.CharField(blank=True, max_length=150, null=True)),
                ('password', models.CharField(blank=True, help_text='base64.encode the Shortcode + Passkey + Timestamp', max_length=250, null=True)),
                ('response_json', models.TextField(blank=True, null=True)),
                ('result_json', models.TextField(blank=True, null=True)),
                ('received_callback', models.BooleanField(default=False)),
                ('callback_received_on', models.DateTimeField(blank=True, null=True)),
                ('queried', models.BooleanField(default=False)),
                ('date_queried', models.DateTimeField(blank=True, null=True)),
                ('query_json', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mpesa Express Payment Request',
                'verbose_name_plural': 'Mpesa Express Payments Requests',
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
    ]
